Section "Device"
    Identifier "TFT35A"
    Driver "fbdev"
    Option "fbdev" "/dev/fb0"
EndSection

Section "Monitor"
    Identifier "TFT35A-Monitor"
EndSection

Section "Screen"
    Identifier "TFT35A-Screen"
    Device "TFT35A"
    Monitor "TFT35A-Monitor"
EndSection
